# Generated by Django 4.2.2 on 2023-06-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='extra_urban_comsumption',
            field=models.CharField(blank=True, max_length=50, verbose_name='Consum exterior'),
        ),
        migrations.AlterField(
            model_name='car',
            name='mixed_comsumption',
            field=models.CharField(blank=True, max_length=50, verbose_name='Consum mixt'),
        ),
        migrations.AlterField(
            model_name='car',
            name='urban_comsumption',
            field=models.CharField(blank=True, max_length=50, verbose_name='Consum oras'),
        ),
    ]
